FROM rabbitmq:3-management

COPY rmq_definitions.json /etc/rabbitmq/definitions.json
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/definitions.json

RUN mkdir -p /etc/rabbitmq/conf.d
RUN chown -R rabbitmq:rabbitmq /etc/rabbitmq/conf.d
COPY rmq-logging.conf /etc/rabbitmq/conf.d

# Add curl for healthcheck
RUN apt-get update
RUN apt-get install -y curl
# also 4369 5671 15671 25672?
EXPOSE 5672 15672
